// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Jest from "@glennsl/bs-jest/src/jest.js";
import * as Data$Coronate from "../Data.bs.js";
import * as Belt_MapString from "bs-platform/lib/es6/belt_MapString.js";
import * as Pairing$Coronate from "../Pairing.bs.js";
import * as TestData$Coronate from "../TestData.bs.js";
import * as Caml_builtin_exceptions from "bs-platform/lib/es6/caml_builtin_exceptions.js";

function loadPairData(tourneyId) {
  var tournament = Belt_MapString.getExn(TestData$Coronate.tournaments, tourneyId);
  var playerIds = tournament[/* playerIds */4];
  var roundList = tournament[/* roundList */5];
  var players = Belt_MapString.reduce(TestData$Coronate.players, Belt_MapString.empty, (function (acc, key, player) {
          if (playerIds.includes(key)) {
            return Belt_MapString.set(acc, key, player);
          } else {
            return acc;
          }
        }));
  return Pairing$Coronate.setUpperHalves(Data$Coronate.Converters[/* createPairingData */10](players, TestData$Coronate.config[/* avoidPairs */0], Data$Coronate.Converters[/* matches2ScoreData */9](Data$Coronate.rounds2Matches(roundList, undefined, /* () */0))));
}

Jest.test("Players have 0 priority of pairing themselves.", (function (param) {
        var pairData = loadPairData("Bye_Round_Tourney____");
        var newb = Belt_MapString.getExn(pairData, "Newbie_McNewberson___");
        var ideal = Pairing$Coronate.calcPairIdeal(newb, newb);
        return Jest.Expect[/* toBe */2](0.0, Jest.Expect[/* expect */0](ideal));
      }));

Jest.describe("The lowest-ranking player is automatically picked for byes.", (function (param) {
        var dataPreBye = loadPairData("Bye_Round_Tourney____");
        var match = Pairing$Coronate.setByePlayer(/* array */[], Data$Coronate.dummy_id, dataPreBye);
        var byedPlayer = match[1];
        var pairData = match[0];
        Jest.test("The lowest-ranking player is removed after bye selection.", (function (param) {
                return Jest.Expect[/* toContain */10]("Newbie_McNewberson___", Jest.Expect[/* not_ */23](Jest.Expect[/* expect */0](Belt_MapString.keysToArray(pairData))));
              }));
        return Jest.test("The lowest-ranking player is returned", (function (param) {
                      if (byedPlayer !== undefined) {
                        return Jest.Expect[/* toBe */2]("Newbie_McNewberson___", Jest.Expect[/* expect */0](byedPlayer[/* id */0]));
                      } else {
                        throw [
                              Caml_builtin_exceptions.assert_failure,
                              /* tuple */[
                                "Pairing_test.re",
                                44,
                                14
                              ]
                            ];
                      }
                    }));
      }));

Jest.test("The bye signup queue works", (function (param) {
        var dataPreBye = loadPairData("Bye_Round_Tourney_2__");
        var byeQueue = /* array */[
          "Newbie_McNewberson___",
          "Joel_Robinson________"
        ];
        var match = Pairing$Coronate.setByePlayer(byeQueue, Data$Coronate.dummy_id, dataPreBye);
        var byedPlayer = match[1];
        if (byedPlayer !== undefined) {
          return Jest.Expect[/* toBe */2]("Joel_Robinson________", Jest.Expect[/* expect */0](byedPlayer[/* id */0]));
        } else {
          throw [
                Caml_builtin_exceptions.assert_failure,
                /* tuple */[
                  "Pairing_test.re",
                  57,
                  12
                ]
              ];
        }
      }));

Jest.test("If all player have (impossibly) played a bye round, the lowest-rated player is picked", (function (param) {
        var dataPreBye = loadPairData("Bye_Tourney_3________");
        var match = Pairing$Coronate.setByePlayer(/* array */[], Data$Coronate.dummy_id, dataPreBye);
        var byedPlayer = match[1];
        if (byedPlayer !== undefined) {
          return Jest.Expect[/* toBe */2]("Newbie_McNewberson___", Jest.Expect[/* expect */0](byedPlayer[/* id */0]));
        } else {
          throw [
                Caml_builtin_exceptions.assert_failure,
                /* tuple */[
                  "Pairing_test.re",
                  68,
                  14
                ]
              ];
        }
      }));

Jest.test("Players are paired correctly in a simple scenario.", (function (param) {
        var pairData = loadPairData("Simple_Pairing_______");
        var matches = Pairing$Coronate.pairPlayers(pairData);
        return Jest.ExpectJs[/* toEqual */12](/* array */[
                    /* tuple */[
                      "Grandy_McMaster______",
                      "Gypsy________________"
                    ],
                    /* tuple */[
                      "Dr_Clayton_Forrester_",
                      "Newbie_McNewberson___"
                    ],
                    /* tuple */[
                      "Joel_Robinson________",
                      "Crow_T_Robot_________"
                    ],
                    /* tuple */[
                      "Tom_Servo____________",
                      "TVs_Frank____________"
                    ]
                  ], Jest.Expect[/* expect */0](matches));
      }));

Jest.test("Players are paired correctly after a draw.", (function (param) {
        var pairData = loadPairData("Pairing_With_Draws___");
        var matches = Pairing$Coronate.pairPlayers(pairData);
        return Jest.Expect[/* toEqual */12](/* array */[
                    /* tuple */[
                      "Grandy_McMaster______",
                      "Gypsy________________"
                    ],
                    /* tuple */[
                      "Dr_Clayton_Forrester_",
                      "Newbie_McNewberson___"
                    ],
                    /* tuple */[
                      "Tom_Servo____________",
                      "TVs_Frank____________"
                    ],
                    /* tuple */[
                      "Joel_Robinson________",
                      "Crow_T_Robot_________"
                    ]
                  ], Jest.Expect[/* expect */0](matches));
      }));

export {
  loadPairData ,
  
}
/*  Not a pure module */
