// Generated by BUCKLESCRIPT VERSION 6.0.3, PLEASE EDIT WITH CARE

import * as Jest from "@glennsl/bs-jest/src/jest.js";
import * as React from "react";
import * as JestDom from "bs-jest-dom/src/JestDom.bs.js";
import * as Utils$Coronate from "../Utils.bs.js";
import * as ReactTestingLibrary from "bs-react-testing-library/src/ReactTestingLibrary.bs.js";

var date = new Date("2000-01-01T13:55:02.573Z");

Jest.test("Date format component works", (function (param) {
        var partial_arg = /* `Str */[
          4153489,
          "Jan 01, 2000"
        ];
        return JestDom.toBeInTheDocument(Jest.Expect[/* expect */0]((function (eta) {
                            var param = undefined;
                            var param$1 = eta;
                            return ReactTestingLibrary.getByText(partial_arg, param, param$1);
                          })(ReactTestingLibrary.render(undefined, undefined, React.createElement(Utils$Coronate.DateFormat[/* make */2], {
                                    date: date
                                  })))));
      }));

Jest.test("Date + time format component works", (function (param) {
        var partial_arg = /* `Str */[
          4153489,
          "Jan 01, 2000, 8:55 AM"
        ];
        return JestDom.toBeInTheDocument(Jest.Expect[/* expect */0]((function (eta) {
                            var param = undefined;
                            var param$1 = eta;
                            return ReactTestingLibrary.getByText(partial_arg, param, param$1);
                          })(ReactTestingLibrary.render(undefined, undefined, React.createElement(Utils$Coronate.DateTimeFormat[/* make */2], {
                                    date: date
                                  })))));
      }));

export {
  date ,
  
}
/* date Not a pure module */
