let crowTRobot: Data.Player.t
let drClaytonForrester: Data.Player.t
let grandyMcMaster: Data.Player.t
let gypsy: Data.Player.t
let joelRobinson: Data.Player.t
let newbieMcNewberson: Data.Player.t
let tomServo: Data.Player.t
let tvsFrank: Data.Player.t

let deletedPlayer: Data.Id.t

let byeRoundTourney: Data.Tournament.t
let byeRoundTourney2: Data.Tournament.t
let byeRoundTourney3: Data.Tournament.t
let simplePairing: Data.Tournament.t
let pairingWithDraws: Data.Tournament.t
let scoreTest: Data.Tournament.t
let deletedPlayerTourney: Data.Tournament.t

let config: Data.Config.t
let players: Data.Id.Map.t<Data.Player.t>
let tournaments: Data.Id.Map.t<Data.Tournament.t>
