let byeRoundTourney: Data.Id.t
let byeRoundTourney2: Data.Id.t
let byeRoundTourney3: Data.Id.t
let simplePairing: Data.Id.t
let pairingWithDraws: Data.Id.t
let scoreTest: Data.Id.t
let deletedPlayerTourney: Data.Id.t

let crowTRobot: Data.Id.t
let drClaytonForrester: Data.Id.t
let grandyMcMaster: Data.Id.t
let gypsy: Data.Id.t
let joelRobinson: Data.Id.t
let newbieMcNewberson: Data.Id.t
let tomServo: Data.Id.t
let tvsFrank: Data.Id.t
let deletedPlayer: Data.Id.t

let config: Data.Config.t
let players: Data.Id.Map.t<Data.Player.t>
let tournaments: Data.Id.Map.t<Data.Tournament.t>
