// Generated by BUCKLESCRIPT VERSION 6.0.3, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Pages$Coronate from "./Pages.bs.js";
import * as Utils$Coronate from "./Utils.bs.js";
import * as Window$Coronate from "./Window.bs.js";
import * as ReasonReactRouter from "reason-react/src/ReasonReactRouter.js";

((require("./side-effects")));

function App(Props) {
  var url = ReasonReactRouter.useUrl(undefined, /* () */0);
  var match = Utils$Coronate.hashPath(url[/* hash */1]);
  var tmp;
  var exit = 0;
  var len = match.length;
  if (len >= 3) {
    exit = 1;
  } else {
    switch (len) {
      case 0 : 
          exit = 1;
          break;
      case 1 : 
          var match$1 = match[0];
          if (match$1 === "") {
            tmp = React.createElement(Pages$Coronate.Splash[/* make */0], { });
          } else {
            exit = 1;
          }
          break;
      case 2 : 
          var match$2 = match[0];
          if (match$2 === "") {
            var match$3 = match[1];
            if (match$3 === "") {
              tmp = React.createElement(Pages$Coronate.Splash[/* make */0], { });
            } else {
              exit = 1;
            }
          } else {
            exit = 1;
          }
          break;
      
    }
  }
  if (exit === 1) {
    tmp = React.createElement(Pages$Coronate.NotFound[/* make */0], { });
  }
  return React.createElement(Window$Coronate.$$Window[/* make */0], {
              children: React.createElement("main", {
                    className: "app__main"
                  }, tmp),
              className: "app"
            });
}

var make = App;

export {
  make ,
  
}
/*  Not a pure module */
