// Generated by BUCKLESCRIPT VERSION 6.0.3, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ElectronUtils$Coronate from "./ElectronUtils.bs.js";

var github_url = "https://github.com/johnridesabike/coronate";

var license_url = "https://github.com/johnridesabike/coronate/blob/master/LICENSE";

function DialogAbout(Props) {
  return React.createElement("article", {
              style: {
                display: "flex",
                width: "100%",
                justifyContent: "space-between"
              }
            }, React.createElement("div", {
                  style: {
                    textAlign: "center",
                    flex: "0 0 48%"
                  }
                }), React.createElement("div", {
                  style: {
                    flex: "0 0 48%"
                  }
                }, React.createElement("h1", {
                      className: "title",
                      style: {
                        textAlign: "left"
                      }
                    }, "Coronate"), React.createElement("p", undefined, "Copyright &copy; 2019 John&nbsp;Jackson"), React.createElement("p", undefined, "Coronate is free software."), React.createElement("p", undefined, React.createElement("a", {
                          href: github_url,
                          onClick: (function (e) {
                              return ElectronUtils$Coronate.ifElectronOpen(e, github_url);
                            })
                        }, "Source code is available"), React.createElement("br", undefined), " under the ", React.createElement("a", {
                          href: license_url,
                          onClick: (function (e) {
                              return ElectronUtils$Coronate.ifElectronOpen(e, license_url);
                            })
                        }, "AGPL v3.0 license"), ".")));
}

var make = DialogAbout;

export {
  github_url ,
  license_url ,
  make ,
  
}
/* react Not a pure module */
