// Generated by BUCKLESCRIPT VERSION 6.0.3, PLEASE EDIT WITH CARE

import * as Localforage from "localforage";

var Numeral = /* module */[];

function Instance(DataType) {
  var create = function (name, storeName) {
    return Localforage.default.createInstance({
                name: name,
                storeName: storeName
              });
  };
  return /* module */[/* create */create];
}

var LocalForage = /* module */[/* Instance */Instance];

var VisuallyHidden = /* module */[];

var Dialog = /* module */[];

var Tabs = /* module */[];

var TabList = /* module */[];

var Tab = /* module */[];

var TabPanels = /* module */[];

var TabPanel = /* module */[];

var ReachTabs = /* module */[
  /* Tabs */Tabs,
  /* TabList */TabList,
  /* Tab */Tab,
  /* TabPanels */TabPanels,
  /* TabPanel */TabPanel
];

export {
  Numeral ,
  LocalForage ,
  VisuallyHidden ,
  Dialog ,
  ReachTabs ,
  
}
/* localforage Not a pure module */
