// Generated by BUCKLESCRIPT VERSION 6.0.3, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Icons$Coronate from "./Icons.bs.js";

var github_url = "https://github.com/johnridesabike/coronate";

var license_url = "https://github.com/johnridesabike/coronate/blob/master/LICENSE";

var issues_url = "https://github.com/johnridesabike/coronate/issues/new";

function PageSplash(Props) {
  return React.createElement("div", {
              className: "splash__splash"
            }, React.createElement("div", {
                  className: "splash__title"
                }, React.createElement("div", {
                      className: "splash__titleIcon"
                    }), React.createElement("div", {
                      className: "splash__titleText"
                    }, React.createElement("h1", {
                          className: "title",
                          style: {
                            fontSize: "40px"
                          }
                        }, "Coronate"), React.createElement("p", {
                          className: "splash__subtitle caption-30"
                        }, "Tournament manager"))), React.createElement("footer", {
                  className: "body-20 splash__footer"
                }, React.createElement("div", {
                      style: {
                        textAlign: "left"
                      }
                    }, React.createElement("p", undefined, "Copyright &copy; 2019 John Jackson."), React.createElement("p", undefined, "Coronate is free software.", React.createElement("br", undefined), React.createElement("a", {
                              href: github_url
                            }, "Source code is available"), " under the ", React.createElement("a", {
                              href: license_url
                            }, "AGPL v3.0 license"), ".")), React.createElement("div", {
                      style: {
                        textAlign: "right"
                      }
                    }, React.createElement("p", undefined, React.createElement("a", {
                              href: issues_url
                            }, "Suggestions and bug reports are welcome.")), React.createElement("p", undefined, "Built with JavaScript and ", React.createElement("a", {
                              href: "https://reactjs.org/"
                            }, "React"), ".", React.createElement("span", {
                              style: {
                                fontSize: "16px"
                              }
                            }, React.createElement(Icons$Coronate.JavaScript[/* make */0], { }), React.createElement(Icons$Coronate.ReactIcon[/* make */0], { }))))));
}

var make = PageSplash;

export {
  github_url ,
  license_url ,
  issues_url ,
  make ,
  
}
/* react Not a pure module */
