// Generated by BUCKLESCRIPT VERSION 6.0.3, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Db$Coronate from "./Db.bs.js";
import * as ReactFeather from "react-feather";
import * as Icons$Coronate from "./Icons.bs.js";
import * as Utils$Coronate from "./Utils.bs.js";
import * as Window$Coronate from "./Window.bs.js";
import * as Electron$Coronate from "./Electron.bs.js";

function Pages$CautionFooter(Props) {
  return React.createElement("aside", {
              className: "caution__container body-20"
            }, React.createElement("p", {
                  className: "caution__text"
                }, "This is beta software. Want to help make it better? Check out the ", React.createElement("span", {
                      "aria-hidden": true,
                      role: "img"
                    }, " 👉 "), Utils$Coronate.Entities[/* nbsp */0], React.createElement("a", {
                      className: "caution__link",
                      href: Utils$Coronate.github_url,
                      onClick: Electron$Coronate.openInBrowser
                    }, "Git repository"), "."));
}

var CautionFooter = /* module */[/* make */Pages$CautionFooter];

function Pages$Splash(Props) {
  return React.createElement(Window$Coronate.Body[/* make */0], {
              children: React.createElement("div", {
                    className: "splash__splash"
                  }, React.createElement("aside", {
                        className: "splash__hint"
                      }, React.createElement("ol", undefined, React.createElement("li", undefined, React.createElement("button", {
                                    className: "button-primary",
                                    onClick: (function (param) {
                                        return Db$Coronate.loadDemoDB(/* () */0);
                                      })
                                  }, "Click here to load the demo data"), "(optional)"), React.createElement("li", undefined, React.createElement(ReactFeather.ArrowLeft, { }), " Select a menu item."), React.createElement("li", undefined, "Start creating your tournaments!")), React.createElement(Utils$Coronate.$$Notification[/* make */0], {
                            children: null,
                            kind: /* Warning */1
                          }, "If you experience glitches or crashes,", React.createElement("br", undefined), "clear your browser cache and try again.")), React.createElement("div", {
                        className: "splash__title"
                      }, React.createElement("div", {
                            className: "splash__titleIcon"
                          }, React.createElement("img", {
                                alt: "",
                                height: "96",
                                src: Utils$Coronate.WebpackAssets[/* logo */0],
                                width: "96"
                              })), React.createElement("div", {
                            className: "splash__titleText"
                          }, React.createElement("h1", {
                                className: "title",
                                style: {
                                  fontSize: "40px"
                                }
                              }, "Coronate"), React.createElement("p", {
                                className: "splash__subtitle caption-30"
                              }, "Tournament manager"))), React.createElement("footer", {
                        className: "body-20 splash__footer"
                      }, React.createElement("div", {
                            style: {
                              textAlign: "left"
                            }
                          }, React.createElement("p", undefined, "Copyright " + (Utils$Coronate.Entities[/* copy */1] + " 2019 John Jackson.")), React.createElement("p", undefined, "Coronate is free software.", React.createElement("br", undefined), React.createElement("a", {
                                    href: Utils$Coronate.github_url,
                                    onClick: Electron$Coronate.openInBrowser
                                  }, "Source code is available"), " under the ", React.createElement("a", {
                                    href: Utils$Coronate.license_url,
                                    onClick: Electron$Coronate.openInBrowser
                                  }, "AGPL v3.0 license"), ".")), React.createElement("div", {
                            style: {
                              textAlign: "right"
                            }
                          }, React.createElement("p", undefined, React.createElement("a", {
                                    href: Utils$Coronate.issues_url,
                                    onClick: Electron$Coronate.openInBrowser
                                  }, "Suggestions and bug reports are welcome.")), React.createElement("p", undefined, "Built with ", React.createElement("a", {
                                    href: "https://reasonml.github.io/reason-react/",
                                    onClick: Electron$Coronate.openInBrowser
                                  }, "ReasonReact"), ". ", React.createElement("span", {
                                    style: {
                                      fontSize: "16px"
                                    }
                                  }, React.createElement(Icons$Coronate.Reason[/* make */0], { }), " ", React.createElement(Icons$Coronate.React[/* make */0], { })))))),
              footerFunc: (function (param) {
                  return React.createElement(Pages$CautionFooter, { });
                })
            });
}

var Splash = /* module */[/* make */Pages$Splash];

function Pages$NotFound(Props) {
  return React.createElement("p", {
              className: "content-area"
            }, "Page not found.");
}

var NotFound = /* module */[/* make */Pages$NotFound];

export {
  CautionFooter ,
  Splash ,
  NotFound ,
  
}
/* react Not a pure module */
