// Generated by BUCKLESCRIPT VERSION 6.0.3, PLEASE EDIT WITH CARE

import * as Cn from "re-classnames/src/Cn.bs.js";
import * as Block from "bs-platform/lib/es6/block.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as ReactFeather from "react-feather";
import * as VisuallyHidden from "@reach/visually-hidden";
import * as ElectronUtils$Coronate from "./ElectronUtils.bs.js";

var windowContext = React.createContext(/* () */0);

function makeProps(value, children, param) {
  return {
          value: value,
          children: children
        };
}

var make = windowContext.Provider;

var Provider = /* module */[
  /* makeProps */makeProps,
  /* make */make
];

function useWindowContext(param) {
  return React.useContext(windowContext);
}

var global_title = "Coronate";

function formatTitle(title) {
  var match = title.length === 0;
  if (match) {
    return global_title;
  } else {
    return title + " - Coronate";
  }
}

function windowReducer(state, action) {
  switch (action.tag | 0) {
    case 0 : 
        return /* record */[
                /* isBlur */action[0],
                /* isDialogOpen */state[/* isDialogOpen */1],
                /* isFullScreen */state[/* isFullScreen */2],
                /* isMaximized */state[/* isMaximized */3],
                /* isSidebarOpen */state[/* isSidebarOpen */4],
                /* title */state[/* title */5]
              ];
    case 1 : 
        return /* record */[
                /* isBlur */state[/* isBlur */0],
                /* isDialogOpen */action[0],
                /* isFullScreen */state[/* isFullScreen */2],
                /* isMaximized */state[/* isMaximized */3],
                /* isSidebarOpen */state[/* isSidebarOpen */4],
                /* title */state[/* title */5]
              ];
    case 2 : 
        return /* record */[
                /* isBlur */state[/* isBlur */0],
                /* isDialogOpen */state[/* isDialogOpen */1],
                /* isFullScreen */action[0],
                /* isMaximized */state[/* isMaximized */3],
                /* isSidebarOpen */state[/* isSidebarOpen */4],
                /* title */state[/* title */5]
              ];
    case 3 : 
        return /* record */[
                /* isBlur */state[/* isBlur */0],
                /* isDialogOpen */state[/* isDialogOpen */1],
                /* isFullScreen */state[/* isFullScreen */2],
                /* isMaximized */action[0],
                /* isSidebarOpen */state[/* isSidebarOpen */4],
                /* title */state[/* title */5]
              ];
    case 4 : 
        return /* record */[
                /* isBlur */state[/* isBlur */0],
                /* isDialogOpen */state[/* isDialogOpen */1],
                /* isFullScreen */state[/* isFullScreen */2],
                /* isMaximized */state[/* isMaximized */3],
                /* isSidebarOpen */action[0],
                /* title */state[/* title */5]
              ];
    case 5 : 
        return /* record */[
                /* isBlur */state[/* isBlur */0],
                /* isDialogOpen */state[/* isDialogOpen */1],
                /* isFullScreen */state[/* isFullScreen */2],
                /* isMaximized */state[/* isMaximized */3],
                /* isSidebarOpen */state[/* isSidebarOpen */4],
                /* title */action[0]
              ];
    
  }
}

var toolbarClasses = Cn.make(/* :: */[
      Cn.ifTrue("macos-button-toolbar", ElectronUtils$Coronate.isMac && ElectronUtils$Coronate.isElectron),
      /* :: */[
        Cn.ifTrue("button-ghost", !(ElectronUtils$Coronate.isMac && ElectronUtils$Coronate.isElectron)),
        /* [] */0
      ]
    ]);

function Window$WindowTitleBar(Props) {
  var state = Props.state;
  var dispatch = Props.dispatch;
  return React.createElement("header", {
              className: Cn.make(/* :: */[
                    "app__header",
                    /* :: */[
                      "double-click-control",
                      /* :: */[
                        Cn.ifTrue("traffic-light-padding", ElectronUtils$Coronate.isElectron && ElectronUtils$Coronate.isMac && !state[/* isFullScreen */2]),
                        /* [] */0
                      ]
                    ]
                  ]),
              onDoubleClick: ElectronUtils$Coronate.macOSDoubleClick
            }, React.createElement("div", undefined, React.createElement(ElectronUtils$Coronate.IfElectron[/* make */0], {
                      children: React.createElement("span", {
                            style: {
                              display: "inline-flex",
                              marginRight: "8px",
                              marginLeft: "4px",
                              alignItems: "center"
                            }
                          }),
                      onlyWin: true
                    }), React.createElement("button", {
                      className: toolbarClasses,
                      onClick: (function (param) {
                          return Curry._1(dispatch, /* SetSidebar */Block.__(4, [!state[/* isSidebarOpen */4]]));
                        })
                    }, React.createElement(ReactFeather.Sidebar, { }), React.createElement(VisuallyHidden, {
                          children: "Toggle sidebar"
                        })), React.createElement("button", {
                      className: toolbarClasses,
                      onClick: (function (param) {
                          return Curry._1(dispatch, /* SetDialog */Block.__(1, [true]));
                        })
                    }, React.createElement(ReactFeather.HelpCircle, { }), React.createElement(VisuallyHidden, {
                          children: "About Coronate"
                        }))), React.createElement("div", {
                  className: Cn.make(/* :: */[
                        "body-20",
                        /* :: */[
                          "double-click-control",
                          /* :: */[
                            Cn.ifTrue("disabled", state[/* isBlur */0]),
                            /* [] */0
                          ]
                        ]
                      ]),
                  style: {
                    left: "0",
                    marginRight: "auto",
                    marginLeft: "auto",
                    position: "absolute",
                    right: "0",
                    textAlign: "center",
                    width: "50%"
                  }
                }, formatTitle(state[/* title */5])));
}

var WindowTitleBar = /* module */[/* make */Window$WindowTitleBar];

var initialWinState = /* record */[
  /* isBlur */false,
  /* isDialogOpen */false,
  /* isFullScreen */false,
  /* isMaximized */false,
  /* isSidebarOpen */true,
  /* title */""
];

export {
  windowContext ,
  Provider ,
  useWindowContext ,
  global_title ,
  formatTitle ,
  initialWinState ,
  windowReducer ,
  toolbarClasses ,
  WindowTitleBar ,
  
}
/* windowContext Not a pure module */
