// Generated by BUCKLESCRIPT VERSION 6.0.3, PLEASE EDIT WITH CARE

import * as Jest from "@glennsl/bs-jest/src/jest.js";
import * as Scoring$Coronate from "../src/Scoring.bs.js";
import * as TestData$Coronate from "../src/TestData.bs.js";

var newb = TestData$Coronate.players["Newbie_McNewberson___"];

var master = TestData$Coronate.players["Grandy_McMaster______"];

Jest.test("K Factor is calculated correctly", (function (param) {
        var masterKFactor = Scoring$Coronate.getKFactor(master[/* matchCount */3]);
        return Jest.Expect[/* toBe */2](8, Jest.Expect[/* expect */0](masterKFactor));
      }));

Jest.test("Ratings are calculated correctly", (function (param) {
        var origRatings_000 = newb[/* rating */4];
        var origRatings_001 = master[/* rating */4];
        var origRatings = /* tuple */[
          origRatings_000,
          origRatings_001
        ];
        var matchCounts_000 = newb[/* matchCount */3];
        var matchCounts_001 = master[/* matchCount */3];
        var matchCounts = /* tuple */[
          matchCounts_000,
          matchCounts_001
        ];
        var newbWon = Scoring$Coronate.calcNewRatings(origRatings, matchCounts, /* tuple */[
              1.0,
              0.0
            ]);
        var masterWon = Scoring$Coronate.calcNewRatings(origRatings, matchCounts, /* tuple */[
              0.0,
              1.0
            ]);
        var draw = Scoring$Coronate.calcNewRatings(origRatings, matchCounts, /* tuple */[
              0.5,
              0.5
            ]);
        return Jest.Expect[/* toEqual */12](/* tuple */[
                    /* tuple */[
                      1600,
                      2592
                    ],
                    /* tuple */[
                      800,
                      2600
                    ],
                    /* tuple */[
                      1200,
                      2596
                    ]
                  ], Jest.Expect[/* expect */0](/* tuple */[
                        newbWon,
                        masterWon,
                        draw
                      ]));
      }));

Jest.test("Ratings never go below 100", (function (param) {
        var match = Scoring$Coronate.calcNewRatings(/* tuple */[
              100,
              100
            ], /* tuple */[
              69,
              69
            ], /* tuple */[
              0.0,
              1.0
            ]);
        return Jest.Expect[/* toBe */2](100, Jest.Expect[/* expect */0](match[0]));
      }));

export {
  newb ,
  master ,
  
}
/* newb Not a pure module */
